# PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-vol
  namespace: daniel2-namespace
spec:
  storageClassName: sc-postgres
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres-vol1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: daniel2-namespace
spec:
  storageClassName: sc-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-postgres
  namespace: daniel2-namespace
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-postgres
  namespace: daniel2-namespace
data:
  postgres.user: postgres
  postgres.password: 130801
  postgres.db: postgresdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: daniel2-namespace
  labels:
    app: postgres-server
spec:
  selector:
    matchLabels:
      app: postgres-server
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - image: postgres:11
        name: postgres-db1
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume1
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: cm-postgres
                key: postgres.user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: cm-postgres
                key: postgres.password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: cm-postgres
                key: postgres.db
      volumes:
      - name: postgres-db-volume1
        persistentVolumeClaim:
           claimName: pvc-postgres